version: '3'
services:
  web-server:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/usr/share/nginx/html
    depends_on:
      - app

  app:
    build: .
    ports:
      - "8081:8080"